# Generated by Django 2.2.4 on 2019-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReciepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_title', models.CharField(max_length=30)),
                ('reciept_file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
