# Generated by Django 2.2.4 on 2019-11-17 03:00

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=20)),
                ('product_category_slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=40, null=True)),
                ('product_slug', models.SlugField(max_length=40)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_description', ckeditor.fields.RichTextField()),
                ('product_cost', models.FloatField()),
                ('product_volume', models.IntegerField()),
                ('product_published_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('product_size_choices', models.CharField(choices=[('Seven', 7), ('Eight', 8), ('Nine', 9)], max_length=20)),
            ],
        ),
    ]
